-
 hosts: iscsi-targets
 remote_user: root
 gather_facts: no

 tasks:
   - name: install targetcli
     yum:
       name: targetcli
       state: latest
   - name: open_firewall
     iptables:
       chain: INPUT
       protocol: tcp
       destination_port: 3260
       jump: ACCEPT
