-
  hosts: 
     - target2
     - target3
     - target4
  remote_user: root
 
  vars:
     iscsi_targets:
        - name: target1
        - name: target2
        - name: target3
     blockdevs:
        - sdb
        - sdc
        - sdd
        - sde

                         
  tasks:
     - name: cleanup old
       shell: targetcli '/iscsi delete iqn.2018-07.local.skytap.target1'
     - name: c1
       shell: targetcli '/backstores/block delete BD1'
     - name: c2
       shell: targetcli '/backstores/block delete OCR'
     - name: c3
       shell: targetcli '/backstores/block delete REDO1'
     - name: c4
       shell: targetcli '/backstores/block delete REDO2'
     - name: savecfg
       shell: 'targetcli saveconfig'
     - name: verifycfg
       shell: 'targetcli ls'
       #     - name: create backstores
       #shell: targetcli '/backstores/block/{{ item.name }}' status ||
       #       targetcli "/backstores/{{ item.mode }}io" create
       #    "{{ item.name }}" "{{ item.backing_store }}" "size={{item.size}}" #"
       #command: "echo {{item}}"
       #register: resp
       #with_items: "{{iscsi_targets}}"
       #     - debug: msg="{{resp}}"
